version: "3"

services:
  ros:
    image: ros2_host
    container_name: ros2
    hostname: ros2
    extra_hosts:
      - "ros2:127.0.1.1"
    user: docker:docker
    group_add:
      - audio
      - dialout
      - sudo
      - video
    environment:
      DISPLAY: ${DISPLAY}
      QT_X11_NO_MITSHM: 1
      NVIDIA_DRIVER_CAPABILITIES: all
      NVIDIA_VISIBLE_DEVICES: all
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${PWD}/packages/ros2:/home/docker/ws/src

    tmpfs:
      - /tmp
    runtime: nvidia
    tty: true
    stdin_open: true
    privileged: true
