version: "3"

services:
  ros:
    image: ros2_host
    container_name: ros2
    hostname: ros2
    extra_hosts:
      - "ros2:127.0.1.1"
    user: docker:docker
    group_add:
      - audio
      - dialout
      - sudo
      - video
    environment:
      DISPLAY: ${DISPLAY}
      XAUTHORITY: /home/docker/.Xauthority
      QT_X11_NO_MITSHM: 1
      NVIDIA_DRIVER_CAPABILITIES: all
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}/.Xauthority:/home/docker/.Xauthority
      - ${PWD}/packages/ros2:/home/docker/ws/src/

    tmpfs:
      - /tmp
    # ports:
      # - 8080:8080
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
    tty: true
    stdin_open: true
    privileged: true
