name: Build image
decscription: Build and push docker image to docker hub

inputs:
  target:
    description: Target platform to build for
    required: true
  distro:
    description: Target distro to build for
    required: true

runs:
  using: composite
  steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Login to docker hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up docker buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: nturt_ros/${{ input.target }}/${{ input.distro }}
        file: nturt_ros/${{ input.target }}/${{ input.distro }}/Dockerfile
        push: true
        tags: nturacing/nturt_ros:${{ input.target }}-${{ input.distro }}
        platforms: linux/amd64,linux/arm64
