name: Build and push docker image to docker hub

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        target: [host, rpi, jetson]
        distro: [base, devel]
        platforms: linux/amd64,linux/arm64
        include:
          - target: rpi
            distro: deploy
            platforms: linux/arm64
          - target: host
            distro: driverless
            platforms: linux/amd64
        exclude:
          - target: jetson
            distro: devel

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: nturt_ros/${{ matrix.target }}/${{ matrix.distro }}
          file: nturt_ros/${{ matrix.target }}/${{ matrix.distro }}/Dockerfile
          push: true
          tags: nturacing/nturt_ros:${{ matrix.target }}-${{ matrix.distro }}
          platforms: ${{ matrix.platforms }}
