name: Build and push docker image to docker hub

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        max-parallel: 1
        target: [host, rpi]
        distro: [base, devel]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract image metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: nturacing/nturt_ros
          tags:

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: nturt_ros/${{ matrix.target }}/${{ matrix.distro }}
          file: nturt_ros/${{ matrix.target }}/${{ matrix.distro }}/Dockerfile
          push: true
          tags: nturacing/nturt_ros:${{ matrix.target }}-${{ matrix.distro }}
          platforms: linux/amd64,linux/arm64
